-- ============================================================
-- La Femme — Entrada automática de estoque ao receber compras
--
-- Cria:
--   * public.movimentos_estoque (histórico/auditoria de estoque);
--   * RPC public.admin_confirmar_recebimento_compra(p_id bigint);
--   * redefinição de public.admin_alterar_status_compra para BLOQUEAR
--     o recebimento pela via genérica (evita marcar mercadoria como
--     recebida sem dar entrada no estoque).
--
-- Convenções:
--   * movimentos_estoque.quantidade é SEMPRE positiva; o sinal vem do
--     `tipo` (ex.: entrada_compra soma, saida_venda subtrai no futuro).
--   * Nesta fase somente `entrada_compra` é gravado. `saida_venda`,
--     ajustes e estorno ficam previstos no CHECK, mas sem fluxo.
--
-- LIMITAÇÃO DOCUMENTADA (desta fase):
--   * a saída por venda (admin_finalizar_pedido) NÃO gera movimento
--     ainda — continua alterando produto_variante.quantidade direto;
--   * a edição administrativa manual de quantidade continua existindo
--     e NÃO gera movimento;
--   * portanto movimentos_estoque NÃO é um ledger completo ainda e sua
--     soma NÃO deve ser tratada como estoque oficial.
--
-- Idempotente. NÃO executar automaticamente: revisar e aplicar
-- manualmente no Supabase (SQL Editor) na etapa de deploy.
-- ============================================================

-- ============================================================
-- 1) Tabela public.movimentos_estoque
-- ============================================================
create table if not exists public.movimentos_estoque (
  id bigint generated by default as identity primary key,
  produto_variante_id bigint not null,
  tipo text not null,
  quantidade integer not null,
  compra_id bigint null,
  item_compra_id bigint null,
  pedido_id bigint null,
  observacao text null,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'movimentos_estoque_produto_variante_id_fkey') then
    alter table public.movimentos_estoque
      add constraint movimentos_estoque_produto_variante_id_fkey
      foreign key (produto_variante_id) references public.produto_variante (id);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'movimentos_estoque_compra_id_fkey') then
    alter table public.movimentos_estoque
      add constraint movimentos_estoque_compra_id_fkey
      foreign key (compra_id) references public.compras (id);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'movimentos_estoque_item_compra_id_fkey') then
    alter table public.movimentos_estoque
      add constraint movimentos_estoque_item_compra_id_fkey
      foreign key (item_compra_id) references public.itens_compra (id);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'movimentos_estoque_pedido_id_fkey') then
    alter table public.movimentos_estoque
      add constraint movimentos_estoque_pedido_id_fkey
      foreign key (pedido_id) references public.pedidos (id);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'movimentos_estoque_tipo_check') then
    alter table public.movimentos_estoque
      add constraint movimentos_estoque_tipo_check
      check (tipo in ('entrada_compra', 'saida_venda', 'ajuste_positivo', 'ajuste_negativo', 'estorno_compra'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'movimentos_estoque_quantidade_check') then
    alter table public.movimentos_estoque
      add constraint movimentos_estoque_quantidade_check check (quantidade > 0);
  end if;
end $$;

-- Idempotência: no máximo UMA entrada_compra por item_compra.
create unique index if not exists movimentos_estoque_entrada_item_uidx
  on public.movimentos_estoque (item_compra_id)
  where tipo = 'entrada_compra';

create index if not exists movimentos_estoque_produto_variante_id_idx
  on public.movimentos_estoque (produto_variante_id);
create index if not exists movimentos_estoque_compra_id_idx
  on public.movimentos_estoque (compra_id);

-- ============================================================
-- 2) RLS + privilégios
-- ============================================================
alter table public.movimentos_estoque enable row level security;

revoke all on table public.movimentos_estoque from public;
revoke all on table public.movimentos_estoque from anon;
revoke all on table public.movimentos_estoque from authenticated;
revoke all on sequence public.movimentos_estoque_id_seq from public, anon, authenticated;

-- ============================================================
-- 3) RPC — admin_confirmar_recebimento_compra
-- ============================================================
-- Entrada automática de estoque (compra de mercadoria pendente):
--   1. valida admin;
--   2. lock da compra (FOR UPDATE);
--   3. valida tipo/status;
--   4. valida itens (>=1, todos vinculados, quantidade > 0);
--   5. valida ausência de entrada prévia (idempotência);
--   6. lock determinístico das variantes (FOR UPDATE, por id);
--   7. soma quantidade por item (movimento por item) e atualiza variante;
--   8. status -> recebida + recebida_em + updated_at.
-- Qualquer falha -> rollback total (transação única).
create or replace function public.admin_confirmar_recebimento_compra(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_status text;
  v_tipo text;
  v_item record;
  v_check bigint;
  v_ids bigint[];
  v_id bigint;
  v_qtd_itens integer := 0;
  v_total_unidades integer := 0;
  v_nao_vinculados jsonb := '[]'::jsonb;
begin
  if not public.is_admin() and auth.role() <> 'service_role' then
    raise exception 'Acesso negado.' using errcode = '42501';
  end if;

  select status, tipo into v_status, v_tipo
    from public.compras
   where id = p_id
     for update;

  if not found then
    return jsonb_build_object('ok', false, 'codigo', 'NAO_ENCONTRADO', 'erro', 'Compra não encontrada.');
  end if;

  if v_tipo <> 'mercadoria' then
    return jsonb_build_object('ok', false, 'codigo', 'TIPO_INVALIDO', 'erro', 'Somente compras de mercadoria geram entrada no estoque.');
  end if;

  if v_status = 'cancelada' then
    return jsonb_build_object('ok', false, 'codigo', 'COMPRA_CANCELADA', 'erro', 'Compra cancelada não pode ser recebida.');
  end if;

  if v_status = 'recebida' then
    return jsonb_build_object('ok', false, 'codigo', 'COMPRA_JA_RECEBIDA', 'erro', 'Compra já recebida.');
  end if;

  if v_status <> 'pendente' then
    return jsonb_build_object('ok', false, 'codigo', 'TRANSICAO_INVALIDA', 'erro', 'Apenas compras pendentes podem ser recebidas.');
  end if;

  select count(*)::int into v_qtd_itens
    from public.itens_compra
   where compra_id = p_id;

  if v_qtd_itens < 1 then
    return jsonb_build_object('ok', false, 'codigo', 'SEM_ITENS', 'erro', 'A compra não possui itens.');
  end if;

  for v_item in
    select ic.id, ic.produto_variante_id, ic.quantidade, ic.descricao, ic.cor, ic.tamanho
      from public.itens_compra ic
     where ic.compra_id = p_id
     order by ic.id
  loop
    if v_item.produto_variante_id is null then
      v_nao_vinculados := v_nao_vinculados || jsonb_build_object(
        'itemId', v_item.id,
        'descricao', v_item.descricao,
        'cor', v_item.cor,
        'tamanho', v_item.tamanho
      );
    elsif v_item.quantidade is null or v_item.quantidade <= 0 then
      return jsonb_build_object('ok', false, 'codigo', 'ITEM_INVALIDO', 'erro', 'Item com quantidade inválida.', 'itemId', v_item.id);
    end if;
  end loop;

  if jsonb_array_length(v_nao_vinculados) > 0 then
    return jsonb_build_object(
      'ok', false,
      'codigo', 'ITENS_NAO_VINCULADOS',
      'erro', 'Todos os itens precisam estar vinculados a uma variante antes da entrada no estoque.',
      'itens', v_nao_vinculados
    );
  end if;

  if exists (
    select 1
      from public.movimentos_estoque m
      join public.itens_compra ic on ic.id = m.item_compra_id
     where ic.compra_id = p_id
       and m.tipo = 'entrada_compra'
  ) then
    return jsonb_build_object('ok', false, 'codigo', 'ENTRADA_DUPLICADA', 'erro', 'Já existe entrada de estoque para esta compra.');
  end if;

  -- Lock determinístico das variantes (ordem por id) para reduzir deadlock.
  select array_agg(distinct ic.produto_variante_id order by ic.produto_variante_id)
    into v_ids
    from public.itens_compra ic
   where ic.compra_id = p_id;

  foreach v_id in array v_ids loop
    select id into v_check
      from public.produto_variante
     where id = v_id
       for update;

    if not found then
      return jsonb_build_object('ok', false, 'codigo', 'VARIANTE_NAO_ENCONTRADA', 'erro', 'Variante vinculada não encontrada.', 'varianteId', v_id);
    end if;
  end loop;

  -- Entrada + movimento por item (mesma variante em itens distintos soma).
  begin
    for v_item in
      select ic.id, ic.produto_variante_id, ic.quantidade
        from public.itens_compra ic
       where ic.compra_id = p_id
       order by ic.id
    loop
      update public.produto_variante
         set quantidade = quantidade + v_item.quantidade,
             updated_at = now()
       where id = v_item.produto_variante_id;

      insert into public.movimentos_estoque (
        produto_variante_id, tipo, quantidade, compra_id, item_compra_id, observacao
      )
      values (
        v_item.produto_variante_id, 'entrada_compra', v_item.quantidade, p_id, v_item.id,
        'Entrada automática por recebimento de compra'
      );

      v_total_unidades := v_total_unidades + v_item.quantidade;
    end loop;
  exception
    when unique_violation then
      return jsonb_build_object('ok', false, 'codigo', 'ENTRADA_DUPLICADA', 'erro', 'Já existe entrada de estoque para esta compra.');
  end;

  update public.compras
     set status = 'recebida',
         recebida_em = now(),
         updated_at = now()
   where id = p_id;

  return jsonb_build_object(
    'ok', true,
    'total_unidades', v_total_unidades,
    'compra', public.admin_obter_compra(p_id)->'compra'
  );
end;
$$;

-- ============================================================
-- 4) RPC — admin_alterar_status_compra (bloqueia recebimento genérico)
-- ============================================================
-- Somente cancelamento segue por aqui. Recebimento de mercadoria deve
-- usar admin_confirmar_recebimento_compra (entrada de estoque).
create or replace function public.admin_alterar_status_compra(p_id bigint, p_status text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_status_atual text;
begin
  if not public.is_admin() and auth.role() <> 'service_role' then
    raise exception 'Acesso negado.' using errcode = '42501';
  end if;

  select status into v_status_atual
    from public.compras
   where id = p_id
     for update;

  if not found then
    return jsonb_build_object('ok', false, 'codigo', 'NAO_ENCONTRADO', 'erro', 'Compra não encontrada.');
  end if;

  if v_status_atual = 'recebida' then
    return jsonb_build_object('ok', false, 'codigo', 'COMPRA_JA_RECEBIDA', 'erro', 'Compra já recebida.');
  end if;

  if v_status_atual = 'cancelada' then
    return jsonb_build_object('ok', false, 'codigo', 'COMPRA_CANCELADA', 'erro', 'Compra já cancelada.');
  end if;

  if p_status is null or p_status not in ('recebida', 'cancelada') then
    return jsonb_build_object('ok', false, 'codigo', 'TRANSICAO_INVALIDA', 'erro', 'Transição de status inválida.');
  end if;

  if p_status = 'recebida' then
    return jsonb_build_object(
      'ok', false,
      'codigo', 'RECEBIMENTO_INVALIDO',
      'erro', 'O recebimento deve ser confirmado pela ação de recebimento (entrada no estoque).'
    );
  end if;

  update public.compras
     set status = 'cancelada',
         cancelada_em = now(),
         updated_at = now()
   where id = p_id;

  return public.admin_obter_compra(p_id);
end;
$$;

-- ============================================================
-- 5) PERMISSÕES
-- ============================================================
revoke all on function public.admin_confirmar_recebimento_compra(bigint) from public;
revoke execute on function public.admin_confirmar_recebimento_compra(bigint) from anon;
grant execute on function public.admin_confirmar_recebimento_compra(bigint) to authenticated, service_role;

revoke all on function public.admin_alterar_status_compra(bigint, text) from public;
revoke execute on function public.admin_alterar_status_compra(bigint, text) from anon;
grant execute on function public.admin_alterar_status_compra(bigint, text) to authenticated, service_role;
