-- ============================================================
-- La Femme — Fase 1 (estrutura): administradores
-- public.admin_users identifica admins vinculados ao auth.users.
-- RLS habilitado e SEM policies -> tabela não é legível publicamente.
-- Acesso futuro acontece apenas via public.is_admin() (SECURITY DEFINER).
-- ============================================================

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

-- UNIQUE por usuário (mesmo admin não pode ser duplicado)
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'admin_users_user_id_key'
  ) then
    alter table public.admin_users
      add constraint admin_users_user_id_key unique (user_id);
  end if;
end
$$;

-- RLS habilitado, sem policies -> anon/authenticated não leem nem escrevem.
alter table public.admin_users enable row level security;
