-- ============================================================
-- La Femme — Compras (Fase 1): fundação de banco
--
-- Cria a estrutura base do módulo de Compras:
--   * public.fornecedores
--   * public.compras
--   * public.itens_compra
--
-- ESCOPO DESTA FASE (deliberadamente SEM estoque):
--   * NÃO cria movimentos_estoque;
--   * NÃO altera produto_variante.quantidade;
--   * NÃO altera pedidos / itens_pedido;
--   * NÃO altera admin_finalizar_pedido nem nenhuma RPC existente;
--   * NÃO implementa custo médio, CMV nem rateio de frete/desconto;
--   * NÃO cria RPC de recebimento;
--   * NÃO cria RPC CRUD (fica para a próxima fase).
--
-- O módulo nasce como registro financeiro/histórico de compras. A
-- integração com estoque será feita no FINAL do projeto de Compras.
--
-- Arquitetura de acesso (igual ao restante do projeto):
--   Frontend -> Server API -> requireAdmin() -> Service Role ->
--   RPC SECURITY DEFINER -> Banco.
--   RLS habilitado e SEM policies; privilégios de tabela/sequência
--   revogados de anon/authenticated/PUBLIC (só service_role escreve).
--
-- updated_at: não existe trigger genérico no projeto; a coluna fica
-- pronta para as RPCs futuras atualizarem explicitamente.
--
-- Idempotente. NÃO executar automaticamente: revisar e aplicar
-- manualmente no Supabase (SQL Editor) na etapa de deploy.
-- ============================================================

-- ============================================================
-- 1) TABELA — public.fornecedores
-- ============================================================
-- Decisões:
--   * nome NÃO é único: nomes iguais podem existir legitimamente.
--   * cnpj é único apenas quando preenchido (índice único parcial);
--     armazenar somente 14 dígitos, sem máscara — a normalização é
--     responsabilidade da API/RPC. Sem validação de dígito
--     verificador nesta fase.
--   * fornecedor é desativado via "ativo" (soft delete), preservando
--     o histórico de compras.
create table if not exists public.fornecedores (
  id bigint generated by default as identity primary key,
  nome text not null,
  cnpj text null,
  telefone text null,
  email text null,
  contato text null,
  observacao text null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'fornecedores_nome_check') then
    alter table public.fornecedores
      add constraint fornecedores_nome_check
      check (char_length(btrim(nome)) between 2 and 120);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'fornecedores_cnpj_check') then
    alter table public.fornecedores
      add constraint fornecedores_cnpj_check
      check (cnpj is null or cnpj ~ '^[0-9]{14}$');
  end if;

  if not exists (select 1 from pg_constraint where conname = 'fornecedores_telefone_check') then
    alter table public.fornecedores
      add constraint fornecedores_telefone_check
      check (telefone is null or char_length(telefone) between 8 and 20);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'fornecedores_email_check') then
    alter table public.fornecedores
      add constraint fornecedores_email_check
      check (
        email is null
        or (
          char_length(email) between 5 and 160
          and email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'
        )
      );
  end if;

  if not exists (select 1 from pg_constraint where conname = 'fornecedores_contato_check') then
    alter table public.fornecedores
      add constraint fornecedores_contato_check
      check (contato is null or char_length(contato) <= 120);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'fornecedores_observacao_check') then
    alter table public.fornecedores
      add constraint fornecedores_observacao_check
      check (observacao is null or char_length(observacao) <= 1000);
  end if;
end $$;

-- Unicidade de CNPJ somente quando preenchido (evita duplicidade óbvia).
create unique index if not exists fornecedores_cnpj_uidx
  on public.fornecedores (cnpj)
  where cnpj is not null;

-- Busca/ordenação por nome e filtro por ativo.
create index if not exists fornecedores_nome_idx on public.fornecedores (nome);
create index if not exists fornecedores_ativo_idx on public.fornecedores (ativo);

alter table public.fornecedores enable row level security;

-- ============================================================
-- 2) TABELA — public.compras
-- ============================================================
-- Suporta dois tipos: 'mercadoria' e 'despesa'.
--   * tipo='mercadoria': itens em itens_compra (com ou sem variante);
--   * tipo='despesa': pode não ter itens (valor no cabeçalho) ou ter
--     itens genéricos; categoria textual padroniza a despesa.
-- Não há tabela de categorias nesta fase (texto livre).
--
-- Status operacional ('pendente' | 'recebida' | 'cancelada'):
--   'recebida' é apenas um estado. Mudar para 'recebida' NÃO altera
--   estoque nesta fase.
--
-- Pagamento ('pendente' | 'pago'): sem parcelas/parcial/contas a pagar.
--
-- Integridade financeira: total = subtotal + frete - desconto é
-- garantido por CHECK no banco. As RPCs futuras calcularão e gravarão
-- os valores no servidor; o frontend nunca é a fonte da verdade.
create table if not exists public.compras (
  id bigint generated by default as identity primary key,
  fornecedor_id bigint null,
  tipo text not null,
  categoria text null,
  descricao text null,
  data_compra date not null default current_date,
  subtotal numeric(10,2) not null default 0,
  frete numeric(10,2) not null default 0,
  desconto numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  forma_pagamento text null,
  status_pagamento text not null default 'pendente',
  vencimento date null,
  pago_em timestamptz null,
  status text not null default 'pendente',
  recebida_em timestamptz null,
  cancelada_em timestamptz null,
  observacao text null,
  comprovante_url text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  -- Fornecedor opcional: despesas podem não ter fornecedor formal.
  -- ON DELETE SET NULL preserva o histórico da compra.
  if not exists (select 1 from pg_constraint where conname = 'compras_fornecedor_id_fkey') then
    alter table public.compras
      add constraint compras_fornecedor_id_fkey
      foreign key (fornecedor_id) references public.fornecedores (id)
      on delete set null;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'compras_tipo_check') then
    alter table public.compras
      add constraint compras_tipo_check
      check (tipo in ('mercadoria', 'despesa'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'compras_status_check') then
    alter table public.compras
      add constraint compras_status_check
      check (status in ('pendente', 'recebida', 'cancelada'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'compras_status_pagamento_check') then
    alter table public.compras
      add constraint compras_status_pagamento_check
      check (status_pagamento in ('pendente', 'pago'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'compras_subtotal_check') then
    alter table public.compras add constraint compras_subtotal_check check (subtotal >= 0);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'compras_frete_check') then
    alter table public.compras add constraint compras_frete_check check (frete >= 0);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'compras_desconto_check') then
    alter table public.compras add constraint compras_desconto_check check (desconto >= 0);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'compras_total_check') then
    alter table public.compras add constraint compras_total_check check (total >= 0);
  end if;

  -- Consistência financeira no banco (numeric é exato). O desconto não
  -- pode deixar o total negativo: isso é consequência de total >= 0
  -- somado à igualdade abaixo.
  if not exists (select 1 from pg_constraint where conname = 'compras_total_coerente_check') then
    alter table public.compras
      add constraint compras_total_coerente_check
      check (total = subtotal + frete - desconto);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'compras_categoria_check') then
    alter table public.compras
      add constraint compras_categoria_check
      check (categoria is null or char_length(categoria) between 1 and 60);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'compras_descricao_check') then
    alter table public.compras
      add constraint compras_descricao_check
      check (descricao is null or char_length(descricao) between 1 and 300);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'compras_forma_pagamento_check') then
    alter table public.compras
      add constraint compras_forma_pagamento_check
      check (forma_pagamento is null or char_length(forma_pagamento) between 1 and 40);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'compras_observacao_check') then
    alter table public.compras
      add constraint compras_observacao_check
      check (observacao is null or char_length(observacao) <= 1000);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'compras_comprovante_url_check') then
    alter table public.compras
      add constraint compras_comprovante_url_check
      check (comprovante_url is null or char_length(comprovante_url) <= 500);
  end if;

  -- Máquina de estados de status x timestamps (coerência total):
  --   pendente  -> recebida_em null  e cancelada_em null
  --   recebida  -> recebida_em set   e cancelada_em null
  --   cancelada -> cancelada_em set  e recebida_em null
  -- Modelo escolhido: cancelamento apenas ANTES do recebimento. Uma
  -- compra recebida não é cancelada nesta fundação (devolução/reversão
  -- de estoque ficam para a fase de integração). Se o negócio precisar
  -- cancelar uma compra recebida no futuro, uma nova migration ajusta
  -- este CHECK explicitamente.
  if not exists (select 1 from pg_constraint where conname = 'compras_status_coerente_check') then
    alter table public.compras
      add constraint compras_status_coerente_check
      check (
        (status = 'pendente'  and recebida_em is null     and cancelada_em is null)
        or (status = 'recebida'  and recebida_em is not null and cancelada_em is null)
        or (status = 'cancelada' and cancelada_em is not null and recebida_em is null)
      );
  end if;

  -- Coerência de pagamento: pago <-> pago_em preenchido.
  --   pendente -> pago_em null
  --   pago     -> pago_em set
  if not exists (select 1 from pg_constraint where conname = 'compras_status_pagamento_coerente_check') then
    alter table public.compras
      add constraint compras_status_pagamento_coerente_check
      check (
        (status_pagamento = 'pago'     and pago_em is not null)
        or (status_pagamento = 'pendente' and pago_em is null)
      );
  end if;
end $$;

-- Índices para consultas/relatórios futuros (filtros mais prováveis).
create index if not exists compras_fornecedor_id_idx on public.compras (fornecedor_id);
create index if not exists compras_tipo_idx on public.compras (tipo);
create index if not exists compras_categoria_idx on public.compras (categoria);
create index if not exists compras_status_idx on public.compras (status);
create index if not exists compras_status_pagamento_idx on public.compras (status_pagamento);
create index if not exists compras_data_compra_idx on public.compras (data_compra);
create index if not exists compras_created_at_idx on public.compras (created_at);

alter table public.compras enable row level security;

-- ============================================================
-- 3) TABELA — public.itens_compra
-- ============================================================
-- Snapshots históricos: descricao, cor, tamanho e valor_unitario
-- preservam o que foi comprado, mesmo que a variante/produto mude
-- depois. produto_variante_id é apenas o vínculo estrutural.
--
-- produto_variante_id é NULLABLE: permite comprar mercadoria nova
-- antes de cadastrá-la no catálogo (vínculo posterior, não nesta fase).
-- Sem ON DELETE CASCADE: proteger o histórico da compra.
--
-- subtotal = quantidade * valor_unitario é garantido por CHECK.
create table if not exists public.itens_compra (
  id bigint generated by default as identity primary key,
  compra_id bigint not null,
  produto_variante_id bigint null,
  descricao text not null,
  cor text null,
  tamanho text null,
  quantidade integer not null,
  valor_unitario numeric(10,2) not null,
  subtotal numeric(10,2) not null,
  created_at timestamptz not null default now()
);

do $$
begin
  -- CASCADE apenas no cabeçalho: uma compra ainda não histórica pode
  -- ser excluída com seus itens. Após histórica, a exclusão será
  -- substituída por cancelamento (RPC futura).
  if not exists (select 1 from pg_constraint where conname = 'itens_compra_compra_id_fkey') then
    alter table public.itens_compra
      add constraint itens_compra_compra_id_fkey
      foreign key (compra_id) references public.compras (id)
      on delete cascade;
  end if;

  -- Sem CASCADE: a variante não pode apagar o histórico de compra.
  if not exists (select 1 from pg_constraint where conname = 'itens_compra_produto_variante_id_fkey') then
    alter table public.itens_compra
      add constraint itens_compra_produto_variante_id_fkey
      foreign key (produto_variante_id) references public.produto_variante (id);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'itens_compra_quantidade_check') then
    alter table public.itens_compra
      add constraint itens_compra_quantidade_check check (quantidade > 0);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'itens_compra_valor_unitario_check') then
    alter table public.itens_compra
      add constraint itens_compra_valor_unitario_check check (valor_unitario >= 0);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'itens_compra_subtotal_check') then
    alter table public.itens_compra
      add constraint itens_compra_subtotal_check check (subtotal >= 0);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'itens_compra_subtotal_coerente_check') then
    alter table public.itens_compra
      add constraint itens_compra_subtotal_coerente_check
      check (subtotal = quantidade * valor_unitario);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'itens_compra_descricao_check') then
    alter table public.itens_compra
      add constraint itens_compra_descricao_check
      check (char_length(btrim(descricao)) between 1 and 300);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'itens_compra_cor_check') then
    alter table public.itens_compra
      add constraint itens_compra_cor_check
      check (cor is null or char_length(cor) <= 60);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'itens_compra_tamanho_check') then
    alter table public.itens_compra
      add constraint itens_compra_tamanho_check
      check (tamanho is null or char_length(tamanho) <= 30);
  end if;
end $$;

create index if not exists itens_compra_compra_id_idx on public.itens_compra (compra_id);
create index if not exists itens_compra_produto_variante_id_idx on public.itens_compra (produto_variante_id);

alter table public.itens_compra enable row level security;

-- ============================================================
-- 4) PRIVILÉGIOS (grants/revokes)
-- ============================================================
-- RLS habilitado e SEM policies já bloqueia anon/authenticated. Como
-- defesa em profundidade, revogamos também os privilégios diretos de
-- tabela e sequência concedidos pelos default ACLs do schema public.
-- service_role (servidor) permanece com acesso; anon/authenticated não.
revoke all on table public.fornecedores from public;
revoke all on table public.fornecedores from anon;
revoke all on table public.fornecedores from authenticated;

revoke all on table public.compras from public;
revoke all on table public.compras from anon;
revoke all on table public.compras from authenticated;

revoke all on table public.itens_compra from public;
revoke all on table public.itens_compra from anon;
revoke all on table public.itens_compra from authenticated;

revoke all on sequence public.fornecedores_id_seq from public, anon, authenticated;
revoke all on sequence public.compras_id_seq from public, anon, authenticated;
revoke all on sequence public.itens_compra_id_seq from public, anon, authenticated;
